
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PaidEmail` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PaidEmail
 * 
 */
export type PaidEmailModel = runtime.Types.Result.DefaultSelection<Prisma.$PaidEmailPayload>

export type AggregatePaidEmail = {
  _count: PaidEmailCountAggregateOutputType | null
  _min: PaidEmailMinAggregateOutputType | null
  _max: PaidEmailMaxAggregateOutputType | null
}

export type PaidEmailMinAggregateOutputType = {
  id: string | null
  email: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PaidEmailMaxAggregateOutputType = {
  id: string | null
  email: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PaidEmailCountAggregateOutputType = {
  id: number
  email: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PaidEmailMinAggregateInputType = {
  id?: true
  email?: true
  createdAt?: true
  updatedAt?: true
}

export type PaidEmailMaxAggregateInputType = {
  id?: true
  email?: true
  createdAt?: true
  updatedAt?: true
}

export type PaidEmailCountAggregateInputType = {
  id?: true
  email?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PaidEmailAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PaidEmail to aggregate.
   */
  where?: Prisma.PaidEmailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PaidEmails to fetch.
   */
  orderBy?: Prisma.PaidEmailOrderByWithRelationInput | Prisma.PaidEmailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PaidEmailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PaidEmails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PaidEmails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PaidEmails
  **/
  _count?: true | PaidEmailCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PaidEmailMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PaidEmailMaxAggregateInputType
}

export type GetPaidEmailAggregateType<T extends PaidEmailAggregateArgs> = {
      [P in keyof T & keyof AggregatePaidEmail]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePaidEmail[P]>
    : Prisma.GetScalarType<T[P], AggregatePaidEmail[P]>
}




export type PaidEmailGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PaidEmailWhereInput
  orderBy?: Prisma.PaidEmailOrderByWithAggregationInput | Prisma.PaidEmailOrderByWithAggregationInput[]
  by: Prisma.PaidEmailScalarFieldEnum[] | Prisma.PaidEmailScalarFieldEnum
  having?: Prisma.PaidEmailScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PaidEmailCountAggregateInputType | true
  _min?: PaidEmailMinAggregateInputType
  _max?: PaidEmailMaxAggregateInputType
}

export type PaidEmailGroupByOutputType = {
  id: string
  email: string
  createdAt: Date
  updatedAt: Date
  _count: PaidEmailCountAggregateOutputType | null
  _min: PaidEmailMinAggregateOutputType | null
  _max: PaidEmailMaxAggregateOutputType | null
}

export type GetPaidEmailGroupByPayload<T extends PaidEmailGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PaidEmailGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PaidEmailGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PaidEmailGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PaidEmailGroupByOutputType[P]>
      }
    >
  >



export type PaidEmailWhereInput = {
  AND?: Prisma.PaidEmailWhereInput | Prisma.PaidEmailWhereInput[]
  OR?: Prisma.PaidEmailWhereInput[]
  NOT?: Prisma.PaidEmailWhereInput | Prisma.PaidEmailWhereInput[]
  id?: Prisma.StringFilter<"PaidEmail"> | string
  email?: Prisma.StringFilter<"PaidEmail"> | string
  createdAt?: Prisma.DateTimeFilter<"PaidEmail"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PaidEmail"> | Date | string
}

export type PaidEmailOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _relevance?: Prisma.PaidEmailOrderByRelevanceInput
}

export type PaidEmailWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  AND?: Prisma.PaidEmailWhereInput | Prisma.PaidEmailWhereInput[]
  OR?: Prisma.PaidEmailWhereInput[]
  NOT?: Prisma.PaidEmailWhereInput | Prisma.PaidEmailWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"PaidEmail"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PaidEmail"> | Date | string
}, "id" | "email">

export type PaidEmailOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PaidEmailCountOrderByAggregateInput
  _max?: Prisma.PaidEmailMaxOrderByAggregateInput
  _min?: Prisma.PaidEmailMinOrderByAggregateInput
}

export type PaidEmailScalarWhereWithAggregatesInput = {
  AND?: Prisma.PaidEmailScalarWhereWithAggregatesInput | Prisma.PaidEmailScalarWhereWithAggregatesInput[]
  OR?: Prisma.PaidEmailScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PaidEmailScalarWhereWithAggregatesInput | Prisma.PaidEmailScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PaidEmail"> | string
  email?: Prisma.StringWithAggregatesFilter<"PaidEmail"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PaidEmail"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"PaidEmail"> | Date | string
}

export type PaidEmailCreateInput = {
  id?: string
  email: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PaidEmailUncheckedCreateInput = {
  id?: string
  email: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PaidEmailUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PaidEmailUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PaidEmailCreateManyInput = {
  id?: string
  email: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PaidEmailUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PaidEmailUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PaidEmailOrderByRelevanceInput = {
  fields: Prisma.PaidEmailOrderByRelevanceFieldEnum | Prisma.PaidEmailOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type PaidEmailCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PaidEmailMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PaidEmailMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}



export type PaidEmailSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["paidEmail"]>



export type PaidEmailSelectScalar = {
  id?: boolean
  email?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PaidEmailOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "email" | "createdAt" | "updatedAt", ExtArgs["result"]["paidEmail"]>

export type $PaidEmailPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PaidEmail"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    email: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["paidEmail"]>
  composites: {}
}

export type PaidEmailGetPayload<S extends boolean | null | undefined | PaidEmailDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PaidEmailPayload, S>

export type PaidEmailCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PaidEmailFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PaidEmailCountAggregateInputType | true
  }

export interface PaidEmailDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PaidEmail'], meta: { name: 'PaidEmail' } }
  /**
   * Find zero or one PaidEmail that matches the filter.
   * @param {PaidEmailFindUniqueArgs} args - Arguments to find a PaidEmail
   * @example
   * // Get one PaidEmail
   * const paidEmail = await prisma.paidEmail.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PaidEmailFindUniqueArgs>(args: Prisma.SelectSubset<T, PaidEmailFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PaidEmailClient<runtime.Types.Result.GetResult<Prisma.$PaidEmailPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PaidEmail that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PaidEmailFindUniqueOrThrowArgs} args - Arguments to find a PaidEmail
   * @example
   * // Get one PaidEmail
   * const paidEmail = await prisma.paidEmail.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PaidEmailFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PaidEmailFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PaidEmailClient<runtime.Types.Result.GetResult<Prisma.$PaidEmailPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PaidEmail that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaidEmailFindFirstArgs} args - Arguments to find a PaidEmail
   * @example
   * // Get one PaidEmail
   * const paidEmail = await prisma.paidEmail.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PaidEmailFindFirstArgs>(args?: Prisma.SelectSubset<T, PaidEmailFindFirstArgs<ExtArgs>>): Prisma.Prisma__PaidEmailClient<runtime.Types.Result.GetResult<Prisma.$PaidEmailPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PaidEmail that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaidEmailFindFirstOrThrowArgs} args - Arguments to find a PaidEmail
   * @example
   * // Get one PaidEmail
   * const paidEmail = await prisma.paidEmail.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PaidEmailFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PaidEmailFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PaidEmailClient<runtime.Types.Result.GetResult<Prisma.$PaidEmailPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PaidEmails that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaidEmailFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PaidEmails
   * const paidEmails = await prisma.paidEmail.findMany()
   * 
   * // Get first 10 PaidEmails
   * const paidEmails = await prisma.paidEmail.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const paidEmailWithIdOnly = await prisma.paidEmail.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PaidEmailFindManyArgs>(args?: Prisma.SelectSubset<T, PaidEmailFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PaidEmailPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PaidEmail.
   * @param {PaidEmailCreateArgs} args - Arguments to create a PaidEmail.
   * @example
   * // Create one PaidEmail
   * const PaidEmail = await prisma.paidEmail.create({
   *   data: {
   *     // ... data to create a PaidEmail
   *   }
   * })
   * 
   */
  create<T extends PaidEmailCreateArgs>(args: Prisma.SelectSubset<T, PaidEmailCreateArgs<ExtArgs>>): Prisma.Prisma__PaidEmailClient<runtime.Types.Result.GetResult<Prisma.$PaidEmailPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PaidEmails.
   * @param {PaidEmailCreateManyArgs} args - Arguments to create many PaidEmails.
   * @example
   * // Create many PaidEmails
   * const paidEmail = await prisma.paidEmail.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PaidEmailCreateManyArgs>(args?: Prisma.SelectSubset<T, PaidEmailCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a PaidEmail.
   * @param {PaidEmailDeleteArgs} args - Arguments to delete one PaidEmail.
   * @example
   * // Delete one PaidEmail
   * const PaidEmail = await prisma.paidEmail.delete({
   *   where: {
   *     // ... filter to delete one PaidEmail
   *   }
   * })
   * 
   */
  delete<T extends PaidEmailDeleteArgs>(args: Prisma.SelectSubset<T, PaidEmailDeleteArgs<ExtArgs>>): Prisma.Prisma__PaidEmailClient<runtime.Types.Result.GetResult<Prisma.$PaidEmailPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PaidEmail.
   * @param {PaidEmailUpdateArgs} args - Arguments to update one PaidEmail.
   * @example
   * // Update one PaidEmail
   * const paidEmail = await prisma.paidEmail.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PaidEmailUpdateArgs>(args: Prisma.SelectSubset<T, PaidEmailUpdateArgs<ExtArgs>>): Prisma.Prisma__PaidEmailClient<runtime.Types.Result.GetResult<Prisma.$PaidEmailPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PaidEmails.
   * @param {PaidEmailDeleteManyArgs} args - Arguments to filter PaidEmails to delete.
   * @example
   * // Delete a few PaidEmails
   * const { count } = await prisma.paidEmail.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PaidEmailDeleteManyArgs>(args?: Prisma.SelectSubset<T, PaidEmailDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PaidEmails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaidEmailUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PaidEmails
   * const paidEmail = await prisma.paidEmail.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PaidEmailUpdateManyArgs>(args: Prisma.SelectSubset<T, PaidEmailUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one PaidEmail.
   * @param {PaidEmailUpsertArgs} args - Arguments to update or create a PaidEmail.
   * @example
   * // Update or create a PaidEmail
   * const paidEmail = await prisma.paidEmail.upsert({
   *   create: {
   *     // ... data to create a PaidEmail
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PaidEmail we want to update
   *   }
   * })
   */
  upsert<T extends PaidEmailUpsertArgs>(args: Prisma.SelectSubset<T, PaidEmailUpsertArgs<ExtArgs>>): Prisma.Prisma__PaidEmailClient<runtime.Types.Result.GetResult<Prisma.$PaidEmailPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PaidEmails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaidEmailCountArgs} args - Arguments to filter PaidEmails to count.
   * @example
   * // Count the number of PaidEmails
   * const count = await prisma.paidEmail.count({
   *   where: {
   *     // ... the filter for the PaidEmails we want to count
   *   }
   * })
  **/
  count<T extends PaidEmailCountArgs>(
    args?: Prisma.Subset<T, PaidEmailCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PaidEmailCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PaidEmail.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaidEmailAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PaidEmailAggregateArgs>(args: Prisma.Subset<T, PaidEmailAggregateArgs>): Prisma.PrismaPromise<GetPaidEmailAggregateType<T>>

  /**
   * Group by PaidEmail.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaidEmailGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PaidEmailGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PaidEmailGroupByArgs['orderBy'] }
      : { orderBy?: PaidEmailGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PaidEmailGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPaidEmailGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PaidEmail model
 */
readonly fields: PaidEmailFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PaidEmail.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PaidEmailClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PaidEmail model
 */
export interface PaidEmailFieldRefs {
  readonly id: Prisma.FieldRef<"PaidEmail", 'String'>
  readonly email: Prisma.FieldRef<"PaidEmail", 'String'>
  readonly createdAt: Prisma.FieldRef<"PaidEmail", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"PaidEmail", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PaidEmail findUnique
 */
export type PaidEmailFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaidEmail
   */
  select?: Prisma.PaidEmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaidEmail
   */
  omit?: Prisma.PaidEmailOmit<ExtArgs> | null
  /**
   * Filter, which PaidEmail to fetch.
   */
  where: Prisma.PaidEmailWhereUniqueInput
}

/**
 * PaidEmail findUniqueOrThrow
 */
export type PaidEmailFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaidEmail
   */
  select?: Prisma.PaidEmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaidEmail
   */
  omit?: Prisma.PaidEmailOmit<ExtArgs> | null
  /**
   * Filter, which PaidEmail to fetch.
   */
  where: Prisma.PaidEmailWhereUniqueInput
}

/**
 * PaidEmail findFirst
 */
export type PaidEmailFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaidEmail
   */
  select?: Prisma.PaidEmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaidEmail
   */
  omit?: Prisma.PaidEmailOmit<ExtArgs> | null
  /**
   * Filter, which PaidEmail to fetch.
   */
  where?: Prisma.PaidEmailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PaidEmails to fetch.
   */
  orderBy?: Prisma.PaidEmailOrderByWithRelationInput | Prisma.PaidEmailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PaidEmails.
   */
  cursor?: Prisma.PaidEmailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PaidEmails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PaidEmails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PaidEmails.
   */
  distinct?: Prisma.PaidEmailScalarFieldEnum | Prisma.PaidEmailScalarFieldEnum[]
}

/**
 * PaidEmail findFirstOrThrow
 */
export type PaidEmailFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaidEmail
   */
  select?: Prisma.PaidEmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaidEmail
   */
  omit?: Prisma.PaidEmailOmit<ExtArgs> | null
  /**
   * Filter, which PaidEmail to fetch.
   */
  where?: Prisma.PaidEmailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PaidEmails to fetch.
   */
  orderBy?: Prisma.PaidEmailOrderByWithRelationInput | Prisma.PaidEmailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PaidEmails.
   */
  cursor?: Prisma.PaidEmailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PaidEmails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PaidEmails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PaidEmails.
   */
  distinct?: Prisma.PaidEmailScalarFieldEnum | Prisma.PaidEmailScalarFieldEnum[]
}

/**
 * PaidEmail findMany
 */
export type PaidEmailFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaidEmail
   */
  select?: Prisma.PaidEmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaidEmail
   */
  omit?: Prisma.PaidEmailOmit<ExtArgs> | null
  /**
   * Filter, which PaidEmails to fetch.
   */
  where?: Prisma.PaidEmailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PaidEmails to fetch.
   */
  orderBy?: Prisma.PaidEmailOrderByWithRelationInput | Prisma.PaidEmailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PaidEmails.
   */
  cursor?: Prisma.PaidEmailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PaidEmails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PaidEmails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PaidEmails.
   */
  distinct?: Prisma.PaidEmailScalarFieldEnum | Prisma.PaidEmailScalarFieldEnum[]
}

/**
 * PaidEmail create
 */
export type PaidEmailCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaidEmail
   */
  select?: Prisma.PaidEmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaidEmail
   */
  omit?: Prisma.PaidEmailOmit<ExtArgs> | null
  /**
   * The data needed to create a PaidEmail.
   */
  data: Prisma.XOR<Prisma.PaidEmailCreateInput, Prisma.PaidEmailUncheckedCreateInput>
}

/**
 * PaidEmail createMany
 */
export type PaidEmailCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PaidEmails.
   */
  data: Prisma.PaidEmailCreateManyInput | Prisma.PaidEmailCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PaidEmail update
 */
export type PaidEmailUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaidEmail
   */
  select?: Prisma.PaidEmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaidEmail
   */
  omit?: Prisma.PaidEmailOmit<ExtArgs> | null
  /**
   * The data needed to update a PaidEmail.
   */
  data: Prisma.XOR<Prisma.PaidEmailUpdateInput, Prisma.PaidEmailUncheckedUpdateInput>
  /**
   * Choose, which PaidEmail to update.
   */
  where: Prisma.PaidEmailWhereUniqueInput
}

/**
 * PaidEmail updateMany
 */
export type PaidEmailUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PaidEmails.
   */
  data: Prisma.XOR<Prisma.PaidEmailUpdateManyMutationInput, Prisma.PaidEmailUncheckedUpdateManyInput>
  /**
   * Filter which PaidEmails to update
   */
  where?: Prisma.PaidEmailWhereInput
  /**
   * Limit how many PaidEmails to update.
   */
  limit?: number
}

/**
 * PaidEmail upsert
 */
export type PaidEmailUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaidEmail
   */
  select?: Prisma.PaidEmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaidEmail
   */
  omit?: Prisma.PaidEmailOmit<ExtArgs> | null
  /**
   * The filter to search for the PaidEmail to update in case it exists.
   */
  where: Prisma.PaidEmailWhereUniqueInput
  /**
   * In case the PaidEmail found by the `where` argument doesn't exist, create a new PaidEmail with this data.
   */
  create: Prisma.XOR<Prisma.PaidEmailCreateInput, Prisma.PaidEmailUncheckedCreateInput>
  /**
   * In case the PaidEmail was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PaidEmailUpdateInput, Prisma.PaidEmailUncheckedUpdateInput>
}

/**
 * PaidEmail delete
 */
export type PaidEmailDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaidEmail
   */
  select?: Prisma.PaidEmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaidEmail
   */
  omit?: Prisma.PaidEmailOmit<ExtArgs> | null
  /**
   * Filter which PaidEmail to delete.
   */
  where: Prisma.PaidEmailWhereUniqueInput
}

/**
 * PaidEmail deleteMany
 */
export type PaidEmailDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PaidEmails to delete
   */
  where?: Prisma.PaidEmailWhereInput
  /**
   * Limit how many PaidEmails to delete.
   */
  limit?: number
}

/**
 * PaidEmail without action
 */
export type PaidEmailDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaidEmail
   */
  select?: Prisma.PaidEmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaidEmail
   */
  omit?: Prisma.PaidEmailOmit<ExtArgs> | null
}
